### ISSUE TITLE
call-dots crashes

### ISSUE THREAD

**Issue by joachimwolff** [open2c/cooltools#218]
Hi,

I am using cooltools call-dots with GM12878 dataset from Rao 2014. I can compute the expected values but if I am calling the dots with: 

`cooltools call-dots --max-loci-separation 2000000 -p 8  -o gm12878.tsv gm12878_int_KR.cool gm12878_exp_raw.tsv`

I only get:

```
Traceback (most recent call last):
  File "/home/wolffj/miniconda3/envs/notebook38/bin/cooltools", line 11, in <module>
    sys.exit(cli())
  File "/home/wolffj/miniconda3/envs/notebook38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/wolffj/miniconda3/envs/notebook38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/wolffj/miniconda3/envs/notebook38/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wolffj/miniconda3/envs/notebook38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wolffj/miniconda3/envs/notebook38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/wolffj/miniconda3/envs/notebook38/lib/python3.8/site-packages/cooltools/cli/call_dots.py", line 315, in call_dots
    gw_hist = dotfinder.scoring_and_histogramming_step(
  File "/home/wolffj/miniconda3/envs/notebook38/lib/python3.8/site-packages/cooltools/dotfinder.py", line 2043, in scoring_and_histogramming_step
    assert (
AssertionError: There are la_exp.horizontal.value in (26007.979, inf], please check the histogram
Command exited with non-zero status 1

```

Any ideas what goes wrong? What histogram is the error message referring to? I searched your docs, but the CLI seems not to offer sth to compute a histogram.

Best,

Joachim

**Comment by sergpolly** [comment]
hey @joachimwolff  !
I'm assuming you've installed the latest "release" of cooltools - i.e. whatever is on PyPI - is that right ?
I'm just double checking, because in the current state of `master`-branch `call-dots` is broken, like some other tools, because we are trying to make everything work with the arbitrary regions - it is a WIP ...

the old version , should work , however ...
could you try adjusting the `--num-lambda-chunks ` parameter , please ? it has to be between 40 and 50 - so maybe 50 would work ?

this parameter shouldn't affect the results, - the only thing it controls is the number of logspaced bins that are used to split the "locally-adjusted expected" (that "donut"-based local intensity estimation) into. it is "hardcoded" (or parameterized) like that because it hard to judge the "dynamic" range of the data a priori .

also - what is the resolution of the input data are you using ? `call-dots` in it current form is really "designed" to reproduce the HiCCUPS results - so it works on resolutions 5, 10 and ~25 kb

**Comment by joachimwolff** [comment]
Hi Sergey,

> hey @joachimwolff !
> I'm assuming you've installed the latest "release" of cooltools - i.e. whatever is on PyPI - is that right ?

I am using the latest conda version, that is version 0.3.2.

> I'm just double checking, because in the current state of `master`-branch `call-dots` is broken, like some other tools, because we are trying to make everything work with the arbitrary regions - it is a WIP ...
> 
> the old version , should work , however ...

What version number is this? And is it available via conda? 0.3.1, 0.3, 0.2 or 0.1?

> could you try adjusting the `--num-lambda-chunks ` parameter , please ? it has to be between 40 and 50 - so maybe 50 would work ?
> 

It seems to me that solved it. I will check it tomorrow again to verify.

> this parameter shouldn't affect the results, - the only thing it controls is the number of logspaced bins that are used to split the "locally-adjusted expected" (that "donut"-based local intensity estimation) into. it is "hardcoded" (or parameterized) like that because it hard to judge the "dynamic" range of the data a priori .
> 
> also - what is the resolution of the input data are you using ? `call-dots` in it current form is really "designed" to reproduce the HiCCUPS results - so it works on resolutions 5, 10 and ~25 kb

The resolution is 10 kb.

Best,

Joachim

**Comment by sergpolly** [comment]
yeah 0.3.2 - is the latest on PyPI as well - I think PyPI is in sync with conda.
there will be a big version jump, as soon as we sort out all of these "arbitrary regions" mess - and hopefully more stable releases will follow

> It seems to me that solved it. Thanks a lot! I will check it tomorrow again to verify.

awesome !

**Comment by joachimwolff** [comment]
> could you try adjusting the --num-lambda-chunks parameter , please ? it has to be between 40 and 50 - so maybe 50 would work ?

That one fixed it. 

Thanks a lot for the help.

Best,

Joachim
