### ISSUE TITLE
input file for cooltools

### ISSUE THREAD

**Issue by BioEpi** [open2c/cooltools#372]
Hello,
    thanks for developing cooltools. I am trying to run cooltools to analyze Hi-C. However, I have several questions about input files.
     1. cooltools eigs-cis requires `TRACK_PATH` : the path to a BedGraph-like file that stores phasing track as track-name named column.
     2. cooltools saddle  requires `TRACK_PATH` and `EXPECTED_PATH`.
     would you like to tell me how to generated both files? 
    thanks in advance.
Best,

**Comment by Phlya** [comment]
Hello!

1. track path for eigenvector annotation should represent some genomic feature that corresponds to active regions in the genome, it is use to choose and orient the eigenvector so positive values correspond to active regions (A compartment). At least for mammals, the most common way to generate this file is to use GC content, since genes have higher GC than genomic average. You can use `cooltools genome gc` to generate such file.
2. Track path for saddles is similar to the above; most typically, the file with the eigenvector is used here, but any track is possible. For expected, use `cooltools expected-cis` or `-trans`, depending on whether you want to generate saddles using cis or trans data.

Hope this helps!

**Comment by Phlya** [comment]
Yes, exactly, that would be the most typical workflow.

**Comment by BioEpi** [comment]
here is my suggestion:
please add some tutorial of how to generate some input files for each command.
Best,

**Comment by nvictus** [comment]
Superseded by #371
