### ISSUE TITLE
pileup returns nans as zeros

### ISSUE THREAD

**Issue by gfudenberg** [open2c/cooltools#406]
Is this the intended behavior? @Phlya @agalitsyna 
https://github.com/open2c/cooltools/blob/48bec4008d765b9e0ee0a72782a04d4bca73e930/cooltools/api/snipping.py#L988

Here's a minimal example of what happens when`np.nan` entries are input to that line:
```python
stack = np.array([[[np.nan]]])
stack = np.array([[[np.nan]]])
stack.shape
(1, 1, 1)

np.nansum([stack, np.transpose(stack, axes=(1, 0, 2))], axis=0)
array([[[0.]]])
```

**Comment by Phlya** [comment]
Mhhh good point... I think this is not intended behaviour, this is there to fill in the bottom triangle of the on-diagonal pileups, since otherwise they would be empty and people would be surprised. I guess the positions of NaNs in the upper triangle need to be recorded, and then equivalently transposed, and set again in the new array... Something like that.

**Comment by golobor** [comment]
A potentially simpler solution:
https://github.com/open2c/cooltools/compare/master...symmetrize-pileups

see an example here:
https://gist.github.com/golobor/cdf86509191515b6e6ae3e4cd6a2f086

**Comment by Phlya** [comment]
Cool, never heard of this function. Need to test, but looks promising!
