### ISSUE TITLE
binedges are not used by make_saddle; use max(digitized) instead

### ISSUE THREAD

**Issue by golobor** [open2c/cooltools#42]
https://github.com/mirnylab/cooltools/blob/34ba9a347010b614f483871baa74d29dbe23dd9d/cooltools/saddle.py#L216

**Comment by gfudenberg** [comment]
I think they are passed b/c the "right outlier values" bin could be empty and hence max(digitized) would give a number of bins that is off by one... would it be strange to make digitized a categorical so that information is passed in the dataframe?

related to this, though, digitized currently puts the max(track) in the "outlier bin", 
![image](https://user-images.githubusercontent.com/19657573/132107319-f135c4fb-aec4-4e73-a53c-6685fc9116a3.png)

https://github.com/open2c/cooltools/blob/ff066aca1cd1569c119cfe74efdb54beee580e20/cooltools/saddle.py#L66

since np.digitize ``bins[i-1] <= x < bins[i]`` for all bins. 

should we modify this to be <= bins[-1]?

**Comment by golobor** [comment]
I agree, max(digitized) should belong to the last bin!

**Comment by gfudenberg** [comment]
great-- this is addressed now, closing!


# re-assign values equal to the max value to bin n
digitized.loc[
        digitized[track_value_col] == np.max(binedges), track_value_col
    ] = n_bins
