### ISSUE TITLE
cooltools saddle plots squeezed 

### ISSUE THREAD

**Issue by Snehal1894** [open2c/cooltools#423]
I ran this command.

cooltools saddle myfile.mcool::/resolutions/100000  EVtrack.cis.vecs.tsv::E1 Cisexpected.cis.tsv -o check-new --strength --fig png --view regions22-hg38 --qrange 0.02 0.98
(Tried the vrange option as well)
The plot we get is : (no errors as such, just Future warning)
![check-new](https://user-images.githubusercontent.com/38363802/222824229-b0020b1c-7f1f-4d17-838b-24aed802074d.png)

**Comment by Michael-Szalay** [comment]
hello,

I also tried out to plot the saddle plot via the python documentation. I also get a squeezed plot:
![image](https://user-images.githubusercontent.com/103572781/228556074-227bd470-0ed0-414c-883e-2120ed0e52e0.png)

I used my data, but the script from the docs:

saddleplot(eigenvector_track,
           interaction_sum/interaction_count,
           N_GROUPS,
           qrange=(Q_LO,Q_HI),
           cbar_kws={'label':'average observed/expected contact frequency'},
           title='test'
          );

**Comment by gfudenberg** [comment]
hi @Michael-Szalay & @Snehal1894 -- what version of python/matplotlib/cooltools are you using?

**Comment by Michael-Szalay** [comment]
I managed to solve it after some tries and errors with the environment. 
For me, it did the trick to install matplotlib, like that in my environment:
conda install matplotlib==3.5.1

before it only contained matplotlib-base 3.6.3 
I think that was the problem, because installing matplotlib==3.5.1 leaded to downgrade matplotlib-base to 3.5.1 as well
then it worked with the plot

PS: because @gfudenberg asked:
python                    3.8.12
matplotlib                3.5.1            
matplotlib-base           3.5.1
cooler                    0.9.1

**Comment by gfudenberg** [comment]
Thank you both for the info, closing as resovled

**Comment by liufuyan2016** [comment]
Dear authors,
I make an strange saddle plot and the barplot parts neighboured the heatmap is all the same. 
Could you help me?
Thank you!

![test saddle cis 100000  6](https://github.com/open2c/cooltools/assets/23466455/f28ec4da-3ed0-4ae6-bb9a-44ada379129d)
