### ISSUE TITLE
min_diag, max_diag question

### ISSUE THREAD

**Issue by kimj50** [open2c/cooltools#440]
Hello cool people,
Thank you for the amazing tool.
I have a question regarding min/max diag parameter in cooltools.api.saddle.saddle
If I understood correctly, these parameters dictate the range of separation used to generate the saddle plot.
Questions:
Is min_diag = 0, the main diagonal?

For example,
If using 2kb-binned matrix, min_diag=3, max_diag=5,
This would mean that the saddle output only considers separation greater than or equal to 6kb and less than or equal to 10kb?

Thank you,
Jun

**Comment by gfudenberg** [comment]
yes min_diag=0 is the main diagonal. Note that the first 2 diagonals are  typically filtered as part of cooler matrix balancing since they can be impacted by molecular byproducts. You can see where the masking happens here: https://github.com/open2c/cooltools/blob/34c99e7b9b0201d14e8d1fbcbd70b1822682ae62/cooltools/api/saddle.py#L199

Closing for now, but feel free to reopen!
