### ISSUE TITLE
cooltools.virtual4c does not write valid .bw files

### ISSUE THREAD

**Issue by StrohD** [open2c/cooltools#498]
```
(base) user@cluster:~/projects/test$ conda activate cooltools
(cooltools) user@cluster:~/projects/test$ cooltools virtual4c -o test --bigwig -p 20 test.mcool::/resolutions/5000 chr1:16545939-16546009
(cooltools) user@cluster:~/projects/test$ ~/tools/kentutils/bigWigInfo test.bw
test.bw is not a big wig file
(cooltools) user@cluster:~/projects/test$ cooltools --version
cooltools, version 0.5.4
(cooltools) user@cluster:~/projects/test$
```

```
ucsc-bedgraphtobigwig     455                  h2a80c09_0    bioconda
```

**Comment by StrohD** [comment]
Fixed in version 0.6.1

**Comment by BenxiaHu** [comment]
I get the same error.
the bigwig file can not be recongzed by IGV.
bad magnic number 0

**Comment by wangmhan** [comment]
Hello, I'm facing the same problem: cannot generate bigwig files. The viewpoint was not working, though I specified it.
cooltools, version 0.7.1

here is my code:
cooltools virtual4c -p 4 --bigwig \
	-o test \
	coolers_library_group/sample.mcool::/resolutions/5000 \
	chr15:61754325-63935880

Any suggestions? Thank you!

**Comment by wangmhan** [comment]
It means although I add viewpoint at the end of the command: chr15:61754325-63935880, the .tsv file start from chr1, not only the restricted region. For example, the head of the tsv file:
chrom   start   end     balanced
chr1    0       5000    nan
chr1    5000    10000   nan
chr1    10000   15000   nan
chr1    15000   20000   nan

I changed the region to a smaller one: chr15:63770000-63780000, but still cannot get bigwig file. 

I previously used "cooltools insulation -p 4 --bigwig" command and it worked well. So that it is not because some packages is missing.

**Comment by StrohD** [comment]
So cooltools works as expected. Please have a look at what a viewpoint is.On 7 Jan 2025 17:59, wangmhan ***@***.***> wrote:
It means although I add viewpoint at the end of the command: chr15:61754325-63935880, the .tsv file start from chr1, not only the restricted region. For example, the head of the tsv file:
chrom   start   end     balanced
chr1    0       5000    nan
chr1    5000    10000   nan
chr1    10000   15000   nan
chr1    15000   20000   nan
I changed the region to a smaller one: chr15:63770000-63780000, but still cannot get bigwig file.
I previously used "cooltools insulation -p 4 --bigwig" command and it worked well. So that it is not because some packages is missing.

**Comment by wangmhan** [comment]
I see.
The problem with bigwig is that there is no bigwig files after I run the command, which I add --bigwig.

**Comment by Phlya** [comment]
OK, sounds like a different problem than reported originally here.
Is there no error?
What version of bioframe do you have installed?
Do you have pybigtools or bedGraphToBigWig installed?

**Comment by wangmhan** [comment]
There was no error messages.

bioframe version: 0.6.1

I have pybedtools and pybigwig installed. Also I managed to run another function of cooltools: cooltools insulation -p 4 --bigwig, and got .bw files. So I don't know why it didn't work with cooltools virtual4c -bigwig?

**Comment by Phlya** [comment]
Can you try updating bioframe to the latest version, or if that doesn't work, to the latest version in the master branch?

**Comment by wangmhan** [comment]
Hi, 
I tried to update bioframe but it doesn't work.

So that I generate the bw files manually. Here is my code:
awk -F"\t" '$4 != "nan" {print $1,$2,$3,$4}' virtual4c_test.tsv > virtual4c_test.bedgraph
vim virtual4c_test.bedgraph #rm head
sort -k1,1 -k2,2n virtual4c_test.bedgraph > virtual4c_test.sorted.bedGraph
awk '!seen[$1,$2,$3]++' virtual4c_test.sorted.bedGraph > virtual4c_test.nodup.bedGraph
bedGraphToBigWig virtual4c_test.nodup.bedGraph chrom_sizes.txt virtual4c_test.bw

In case someone face the same problem.

Just realised the argument was not working for insulation as well... I used the same way to generate bigwig file manually!
