### ISSUE TITLE
coverage calculation with ignore_diags=0 double counts main diagonal

### ISSUE THREAD

**Issue by sergpolly** [open2c/cooltools#99]
we've been doing some analysis on coolers based on filtered pairs (>1kb only) and thus we were setting `ignore_diags=0` everywhere - for balancing, for coverage calculations etc ...

in the course of action - an anomaly was detected, which I think is related to this awesome way of counting coverage/marginals/# of interactions per bin:
https://github.com/mirnylab/cooltools/blob/06767990ab62d9e9291522502d5b4c410e01b786/cooltools/coverage.py#L40

this is of course related and connected to :
https://github.com/mirnylab/cooler/blob/843dadca5ef58e3b794dbaf23430082c9a634532/cooler/balance.py#L63

here is a not so minimal example:
```python
import cooler
from cooltools.coverage import get_coverage

clr = cooler.Cooler('/path/to/lowresolution.cool') # 1mb or 0.5mb 

# coverage  calculation - naive way ...
raw_row_sums = clr.matrix(balance=False)[:].sum(axis=1)
print(raw_row_sums)

# same thing but using bincount of streaming
# pixels ... (same as in marginals calculations in cooler)
covs = get_coverage(clr, ignore_diags=0 )
# extract total global coverage:
cov_tot = 2*covs.astype(int)[1]
print(cov_tot)
print("results should be slightly off ...")
```
so, the coverage/marginals calculated 2 different ways is different - but shouldn't be ...
a potential cause, continuation of the "not so minimal example":

```python
# i think the problem is due to double-counting the diagonal ...
diag = clr.matrix(balance=False)[:].diagonal()
correct_cov = cov_tot - diag

print("this should look identical to the 1st line ...")
print(correct_cov)
print("are all value identical ? - ")
print(~(correct_cov - rows).any())
print("wtf ? let's print those that are still different ...")
idx = np.nonzero(correct_cov - rows)
print(rows[idx])
print(correct_cov[idx])
print("seems like 1-off - confirm - max difference:")
print(np.abs(correct_cov - rows).max())
print("maybe some funky 2*cov.astype(int) ...")
```

so, after correcting with the `diag` - things are still `~1` off here and there - which we could not explain (round off error due to `2*cov.astype(int)` ?!) - but it looks much closer now...

we typically `ignore_diags>1` everywhere - so this probably went unnoticed ...
but seems like an issue to me...

also - why https://github.com/mirnylab/cooltools/blob/06767990ab62d9e9291522502d5b4c410e01b786/cooltools/coverage.py#L43
?
for upper triangle matrix - there is no need to divide or am i missing something ?

@nvictus @golobor @mimakaev @itsameercat who is around these days ? I don't want to PR anything until you confirm that this is indeed an issue

**Comment by sergpolly** [comment]
potential PRs for cooler:

```python
def _marginalize(chunk, data):
    n = len(chunk["bins"]["chrom"])
    pixels = chunk["pixels"]
    marg = np.bincount(pixels["bin1_id"], weights=data, minlength=n) + np.bincount(
        pixels["bin2_id"], weights=data, minlength=n
    )
    # subtract diagonal values when applicable ...
    idx_to_be_corrected = pixels["bin1_id"][pixels["bin1_id"]==pixels["bin2_id"]]
    marg[idx_to_be_corrected] = marg[idx_to_be_corrected] - data[pixels["bin1_id"]==pixels["bin2_id"]]

    return marg

```
or maybe something like https://github.com/mirnylab/cooler/blob/843dadca5ef58e3b794dbaf23430082c9a634532/cooler/balance.py#L85

 subtract the diag after `marg` is calculated :
`marg = marg - diag`

where diag is something like (https://github.com/mirnylab/cooler/blob/843dadca5ef58e3b794dbaf23430082c9a634532/cooler/balance.py#L216):
```python
        diag = (
            split(clr, spans=spans, map=map, use_lock=use_lock)  # noqa
            .prepare(_init)
            .pipe(extract_counts_bin1_eq_bin2)
        )
```
not sure i can come up with anything nicer

**Comment by sergpolly** [comment]
although i'm afraid a lot of people would think that
`clr.matrix(balance=False)[:].sum(axis=1)` - is the right way to get coverage ...

is there any history ? was someone at some point counting pairs with `pixel["bin1_id"]<=pixel["bin2_id"]` PLUS their symmetric counterpart for the main diagonal ?

anyhow, thank you @mimakaev for explanation

**Comment by nvictus** [comment]
Hi Sergey,

Yes, I think it's a matter of what you're asking for. As Max was saying, this formula

```
(
    np.bincount(pixels['bin1_id'], weights=pixel_weights, minlength=n_bins) +
     np.bincount(pixels['bin2_id'], weights=pixel_weights, minlength=n_bins)
)
```

will ultimately double-count every upper triangular pixel, including those on the main diagonal. If you want the mathematical matrix row/column sum, then this almost does the right thing, except you want main diagonal pixels to be counted just once. You could fix it with some filtering, but as Max, argues, it may not reflect what coverage means. We don't worry about this in balancing anyway because we always ignore the main diagonal.

If you want a track that corresponds to read coverage, where every read counts contributes a total "weight" of 1 to the coverage, you can get that by counting every read twice and dividing the result by 2 as in `coverage.py`.

**Comment by sergpolly** [comment]
thanks @nvictus !
this has been actually bothering me for a while - in terms of understanding and such..
i did some slides about it https://docs.google.com/presentation/d/1yZxVhuYdyAMaxjTTABFzaqkXiA16ShBggb8lz9eFFJw/edit?usp=sharing

**Comment by kimj50** [comment]
Hi I'm a phd student at nyu in biology department, learning to analyze hic data.
I wasn't sure where to shoot this question, but seems related here.
Is it 'incorrect' to include the main diagonal in ICE balancing (ie if included, does the balanced matrix not satisfy 'equal visibility' property)?
Thank you - Jun

**Comment by mimakaev** [comment]
Hi Jun, 

There are several reasons to remove the main diagonal / nearby reads. 

First, there is a reason to remove the reads less than a few kb because many (often most) of them are artifacts, and because at the scale of restriction fragment lengths, implicit assumptions of the Hi-C protocol start to break down. 

Second, the main diagonal even after balancing is sensitive to the restriction fragment density. If there are more restriction fragments, they are on average closer to each other, and each produce more counts. Second diagonal is mildly affected by this too, but third+ are unaffected. See attached image from one of my presentations. 

![image](https://user-images.githubusercontent.com/9454715/71733131-d7a08180-2e16-11ea-8a6b-a05968c30ed7.png)

**Comment by kimj50** [comment]
Thank you! - Jun

**Comment by golobor** [comment]
@sergpolly , @nvictus  - what's the status? In any case, it looks like a discussion point?..

**Comment by sergpolly** [comment]
we agreed on it in the current implementation in `coverage`
